// src/utils/constants.js
export const DEFAULT_PENATUA = { '1': "Penatua Felipus Sanam", '2': "Penatua Antonio Lana’in", '3': "Penatua Tomas Tefa", '4': "Penatua Yosina Tefa", '5': "Penatua Agrida Banunaek", '6': "Penatua Aris Misa" };
export const DEFAULT_CHURCH_PROFILE = { sinode: "GEREJA MASEHI INJILI DI TIMOR (GMIT)", klasis: "", jemaat: "NAMA GEREJA", mataJemaat: "", alamat: "Alamat Gereja", namaSekretaris: "Nama Sekretaris" };
export const PEKERJAAN_LIST = ["Tidak/Belum bekerja", "Ibu Rumah Tangga", "Pelajar", "Mahasiswa", "Pensiunan", "PNS", "TNI", "POLRI", "Tenaga Kontrak/Honorer", "Karyawan Swasta", "Pembantu Rumah Tangga", "Buruh/Serabutan", "Petani", "Peternak", "Nelayan", "Pedagang", "Pengrajin", "Penjahit", "Tukang Cukur", "Seniman", "Konsultan", "Kontraktor", "Pekerja Migran", "Wiraswasta lainnya", "Guru", "Dosen", "Pendeta", "Dokter", "Bidan/Perawat", "Lainnya"];
export const KATEGORI_PELAYANAN = ["Semua Kategori", "Lansia Laki-laki (>= 60 tahun)", "Lansia Perempuan (>= 60 tahun)", "Bapak GMIT (35-59 tahun)", "Perempuan GMIT (35-59 tahun)", "Pemuda Laki-laki (17-34 tahun)", "Pemuda Perempuan (17-34 tahun)", "Teruna Laki-laki (15-16 tahun)", "Teruna Perempuan (15-16 tahun)", "Remaja Laki-laki (12-14 tahun)", "Remaja Perempuan (12-14 tahun)", "Anak-anak Laki-laki (5-11 tahun)", "Anak-anak Perempuan (5-11 tahun)", "Balita Laki-laki (0-4 tahun)", "Balita Perempuan (0-4 tahun)"];
export const NAMA_BULAN = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"];

export const JEMAAT_HEADERS = ["ID KK", "Kepala Keluarga", "No Rayon", "Urutan KK", "Bentuk Rumah", "Status Rumah", "Penatua Rayon", "No Anggota", "ID Jemaat", "Nama Lengkap", "NIK", "Jenis Kelamin", "Golongan Darah", "Tempat Lahir", "Tanggal Lahir", "Usia", "Alamat Domisili", "Suku Ayah", "Suku Ibu", "Status Keluarga", "Baptis", "Gereja Baptis", "Tgl Baptis", "Pendeta Baptis", "Sidi", "Gereja Sidi", "Tgl Sidi", "Pendeta Sidi", "Nikah", "Jenis Nikah", "Gereja Nikah", "Tgl Nikah", "Pendeta Nikah", "Pendidikan", "Pekerjaan", "Penghasilan", "Asuransi Kesehatan", "Jaminan", "Janda/Duda", "Yatim/Piatu", "Disabilitas", "Jenis Disabilitas", "Jabatan di Jemaat", "Jabatan di Masyarakat", "Status Keanggotaan", "Tanggal Kematian", "Tanggal Penguburan", "Asal Jemaat", "Tanggal Masuk", "Pindah Ke Gereja", "Tanggal Pindah"];
export const JEMAAT_HEADER_MAP = { "ID KK": "idKk", "Kepala Keluarga": "kepalaKeluarga", "No Rayon": "noRayon", "Urutan KK": "urutanKk", "Bentuk Rumah": "bentukRumah", "Status Rumah": "statusRumah", "Penatua Rayon": "penatua", "No Anggota": "noAnggota", "ID Jemaat": "idJemaat", "Nama Lengkap": "namaLengkap", "NIK": "nik", "Jenis Kelamin": "jk", "Golongan Darah": "goldar", "Tempat Lahir": "tempatLahir", "Tanggal Lahir": "tanggalLahir", "Alamat Domisili": "alamat", "Suku Ayah": "sukuAyah", "Suku Ibu": "sukuIbu", "Status Keluarga": "statusKeluarga", "Baptis": "baptis", "Nama Gereja Baptis": "gerejaBaptis", "Tanggal Baptis": "tanggalBaptis", "Pendeta yang Baptis": "pendetaBaptis", "Sudah Sidi": "sidi", "Nama Gereja Sidi": "gerejaSidi", "Tanggal Sidi": "tanggalSidi", "Pendeta yang Sidi": "pendetaSidi", "Sudah Nikah": "nikah", "Nama Gereja Pemberkatan Nikah": "gerejaNikah", "Tanggal Pemberkatan Nikah": "tanggalNikah", "Pendeta yang Berkat Nikah": "pendetaNikah", "Jenis Nikah": "jenisNikah", "Pendidikan": "pendidikan", "Pekerjaan": "pekerjaan", "Penghasilan": "penghasilan", "Asuransi Kesehatan": "asuransi", "Jaminan": "jaminan", "Janda/Duda": "jandaDuda", "Yatim Piatu": "yatimPiatu", "Yatim/Piatu": "yatimPiatu", "Disabilitas": "disabilitas", "Jenis Disabilitas": "jenisDisabilitas", "Jabatan dalam Jemaat": "jabatanJemaat", "Jabatan di Jemaat": "jabatanJemaat", "Jabatan dalam Masyarakat": "jabatanMasyarakat", "Jabatan di Masyarakat": "jabatanMasyarakat", "Status Keanggotaan": "statusKeanggotaan", "Tanggal Kematian": "tanggalKematian", "Tanggal Penguburan": "tanggalPenguburan", "Asal Jemaat": "asalJemaat", "Tanggal Masuk": "tanggalMasuk", "Pindah Ke Gereja": "pindahKeJemaat", "Tanggal Pindah": "tanggalPindah" };

export const MAJELIS_HEADERS = ["Nomor Rayon", "Nama Lengkap", "Nama Panggilan", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Status Menikah", "Pekerjaan", "Jabatan di Masyarakat", "Jabatan Pelayanan", "Jumlah Saudara", "Anak Ke", "Golongan Darah", "Gereja Baptis", "Tanggal Baptis", "Gereja Sidi", "Tanggal Sidi", "Gereja Nikah", "Tanggal Nikah", "Nama Ayah", "Nama Ibu", "Nama Suami/Istri", "Tempat Lahir Pasangan", "Tanggal Lahir Pasangan", "Pekerjaan Pasangan", "Gereja Baptis Pasangan", "Tanggal Baptis Pasangan", "Gereja Sidi Pasangan", "Tanggal Sidi Pasangan", "Nama SD", "Tahun Tamat SD", "Nama SMP", "Tahun Tamat SMP", "Nama SMA", "Tahun Tamat SMA", "Nama PT", "Tahun Lulus PT", "Pernah melayani di Gereja?", "Jabatan Lama", "Periode Pelayanan"];
export const MAJELIS_HEADER_MAP = { "Nomor Rayon": "noRayon", "Nama Lengkap": "namaLengkap", "Nama Panggilan": "namaPanggilan", "Tempat Lahir": "tempatLahir", "Tanggal Lahir": "tanggalLahir", "Jenis Kelamin": "jk", "Status Menikah": "statusMenikah", "Pekerjaan": "pekerjaan", "Jabatan di Masyarakat": "jabatanMasyarakat", "Jabatan Pelayanan": "jabatanPelayanan", "Jumlah Saudara": "jumlahSaudara", "Anak Ke": "anakKe", "Golongan Darah": "goldar", "Gereja Baptis": "gerejaBaptis", "Tanggal Baptis": "tanggalBaptis", "Gereja Sidi": "gerejaSidi", "Tanggal Sidi": "tanggalSidi", "Gereja Nikah": "gerejaNikah", "Tanggal Nikah": "tanggalNikah", "Nama Ayah": "namaAyah", "Nama Ibu": "namaIbu", "Nama Suami/Istri": "namaPasangan", "Tempat Lahir Pasangan": "tempatLahirPasangan", "Tanggal Lahir Pasangan": "tanggalLahirPasangan", "Pekerjaan Pasangan": "pekerjaanPasangan", "Gereja Baptis Pasangan": "gerejaBaptisPasangan", "Tanggal Baptis Pasangan": "tanggalBaptisPasangan", "Gereja Sidi Pasangan": "gerejaSidiPasangan", "Tanggal Sidi Pasangan": "tanggalSidiPasangan", "Nama SD": "namaSD", "Tahun Tamat SD": "tahunSD", "Nama SMP": "namaSMP", "Tahun Tamat SMP": "tahunSMA", "Nama SMA": "namaSMA", "Tahun Tamat SMA": "tahunSMA", "Nama PT": "namaPT", "Tahun Lulus PT": "tahunPT", "Pernah melayani di Gereja?": "pernahMelayani", "Jabatan Lama": "jabatanLama", "Periode Pelayanan": "periodePelayanan" };

export const FORM_MAJELIS = [
  {t: 'Profil Dasar', f: [
    {l:'Nomor Rayon', k:'noRayon', t:'sel', opts:['1','2','3','4','5','6','7','8','9','10']}, {l:'Nama Lengkap', k:'namaLengkap', req:true}, {l:'Nama Panggilan', k:'namaPanggilan'}, {l:'Tempat Lahir', k:'tempatLahir'}, {l:'Tanggal Lahir', k:'tanggalLahir', t:'date'}, {l:'Jenis Kelamin', k:'jk', t:'sel', opts:['Laki-laki', 'Perempuan']},
    {l:'Status Menikah', k:'statusMenikah', t:'chk', span:2, opts:['Menikah/Nikah Adat', 'Menikah/Nikah Masehi', 'Menikah/BS/Catatan Sipil']}, {l:'Pekerjaan', k:'pekerjaan', t:'sel', opts:PEKERJAAN_LIST}, {l:'Jabatan Masy', k:'jabatanMasyarakat'}, {l:'Jabatan Pelayanan', k:'jabatanPelayanan', t:'sel', opts:['Penatua', 'Diaken', 'Pengajar', 'Koster']}, {l:'Jumlah Sdr', k:'jumlahSaudara', t:'num'}, {l:'Anak Ke-', k:'anakKe', t:'num'}, {l:'Gol Darah', k:'goldar', t:'sel', opts:['A', 'B', 'AB', 'O', 'Tidak Tahu']}
  ]},
  {t: 'Riwayat Agama', f: [
    {l:'Gereja Baptis', k:'gerejaBaptis'}, {l:'Tgl Baptis', k:'tanggalBaptis', t:'date'}, {l:'Gereja Sidi', k:'gerejaSidi'}, {l:'Tgl Sidi', k:'tanggalSidi', t:'date'}, {l:'Gereja Nikah', k:'gerejaNikah'}, {l:'Tgl Nikah', k:'tanggalNikah', t:'date'}
  ]},
  {t: 'Data Pasangan & Orang Tua', f: [
    {l:'Nama Ayah', k:'namaAyah'}, {l:'Nama Ibu', k:'namaIbu'}, {l:'Nama Suami/Istri', k:'namaPasangan'}, {l:'Tempat Lahir Pasangan', k:'tempatLahirPasangan'}, {l:'Tgl Lahir Pasangan', k:'tanggalLahirPasangan', t:'date'}, {l:'Pekerjaan Pasangan', k:'pekerjaanPasangan', t:'sel', opts:PEKERJAAN_LIST},
    {l:'Gereja Baptis Pasangan', k:'gerejaBaptisPasangan'}, {l:'Tgl Baptis Pasangan', k:'tanggalBaptisPasangan', t:'date'}, {l:'Gereja Sidi Pasangan', k:'gerejaSidiPasangan'}, {l:'Tgl Sidi Pasangan', k:'tanggalSidiPasangan', t:'date'}
  ]},
  {t: 'Pendidikan & Pelayanan', f: [
    {l:'Nama SD', k:'namaSD'}, {l:'Tahun SD', k:'tahunSD', t:'num'}, {l:'Nama SMP', k:'namaSMP'}, {l:'Tahun SMP', k:'tahunSMP', t:'num'}, {l:'Nama SMA', k:'namaSMA'}, {l:'Tahun SMA', k:'tahunSMA', t:'num'}, {l:'Nama PT', k:'namaPT'}, {l:'Tahun PT', k:'tahunPT', t:'num'},
    {l:'Pernah melayani?', k:'pernahMelayani'}, {l:'Jabatan Lama', k:'jabatanLama'}, {l:'Periode Pelayanan', k:'periodePelayanan'}
  ]}
];

export const JEMAAT_FIELDS_PRIBADI = [
  { name: 'noAnggota', label: 'No Anggota Keluarga Ke-', type: 'select', req: true, opts: [] },
  { name: 'namaLengkap', label: 'Nama Lengkap', req: true }, { name: 'nik', label: 'NIK' }, { name: 'jk', label: 'Jenis Kelamin', type: 'select', opts: ['Laki-laki', 'Perempuan'] },
  { name: 'goldar', label: 'Golongan Darah', type: 'select', opts: ['A', 'B', 'AB', 'O', 'Tidak Tahu'] }, { name: 'tempatLahir', label: 'Tempat Lahir' }, { name: 'tanggalLahir', label: 'Tanggal Lahir', type: 'date' },
  { name: 'alamat', label: 'Alamat Domisili Lengkap', span: 2 }, { name: 'sukuAyah', label: 'Suku Ayah' }, { name: 'sukuIbu', label: 'Suku Ibu' },
  { name: 'statusKeluarga', label: 'Status Dalam Keluarga', type: 'select', span: 2, opts: ['Kepala Keluarga', 'Istri', 'Anak kandung', 'Anak Angkat/asuh', 'Orangtua/Mertua', 'Kakek/Nenek', 'Saudara/Adik/Kakak', 'Cucu', 'Keponakan', 'Menantu', 'Famili/ipar', 'Lain-lain/Kost/Karyawan/Pembantu'] }
];

export const JEMAAT_EDU = [
  { name: 'pendidikan', label: 'Pendidikan', type: 'select', opts: ['Tidak/Belum Sekolah', 'Tidak Tamat SD', 'SD', 'SMP/sederajat', 'SMA/sederajat', 'D I', 'D II', 'D III', 'D IV', 'S1', 'S2', 'S3'] },
  { name: 'pekerjaan', label: 'Pekerjaan', type: 'select', opts: PEKERJAAN_LIST }, { name: 'penghasilan', label: 'Penghasilan', type: 'select', opts: ['Tidak/belum ada penghasilan', 'dibawah Rp. 1 juta', 'Rp. 1 juta s/d Rp. 2.5 juta', 'Rp. 2.5 juta s/d Rp. 5 juta', 'diatas Rp. 5 juta'] }
];